/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: artasadmemon (https://sketchfab.com/artasadmemon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/gargoyle-and-shapes-ca133a78c1424b9a9d647fceb2631bd1
title: Gargoyle and Shapes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { editable as e } from '@theatre/r3f'

const Gargoyle = () => {
  const { nodes, materials } = useGLTF('./models/gargoyle/scene.gltf')
  return (
    <e.group theatreKey='Gargoyle'  dispose={null} rotation={[0, 0, 0]}>
      <group scale={0.23}>
        <group>
          <group position={[1.76, 1.83, -1.04]} rotation={[Math.PI / 2, 0, 0]} scale={0.31}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-1.2, 3.1, -33.47]} rotation={[Math.PI / 2, 0, 0]} scale={7.8}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-0.55, 1.48, -0.91]}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} />
          </group>
          <group position={[1.3, 1.39, -0.21]} rotation={[1.69, 0.88, -1.07]} scale={0.33}>
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.002']} />
          </group>
          <group position={[0, -.47, 0.5]} scale={0.17}>
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-1.99, 1.43, 0]} scale={0.13}>
            <mesh geometry={nodes.Object_14.geometry} material={materials['Material.006']} />
          </group>
          <group position={[-1, -0.97, -1.91]} scale={0.71}>
            <mesh geometry={nodes.Object_16.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_19.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.material_0} />
          </group>
          <group position={[-1.45, -0.66, -0.25]} scale={1.8}>
            <mesh geometry={nodes.Object_23.geometry} material={materials['Material.002']} />
          </group>
          <group position={[1.65, 0.38, -0.25]} scale={2.23}>
            <mesh geometry={nodes.Object_25.geometry} material={materials.Material} />
          </group>
          <group position={[0, 0.04, -1.19]} scale={1.25}>
            <mesh geometry={nodes.Object_27.geometry} material={materials['Material.002']} />
          </group>
          <group position={[0, 0.04, -1.51]}>
            <mesh geometry={nodes.Object_29.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-1.56, 0.35, 0]}>
            <mesh geometry={nodes.Object_31.geometry} material={materials.material_0} />
          </group>
          <group position={[1.17, -0.9, 0]}>
            <mesh geometry={nodes.Object_33.geometry} material={materials.material_0} />
          </group>
          <group position={[-1.15, 1.23, -1.71]} rotation={[Math.PI / 2, 0, 0]} scale={1.1}>
            <mesh geometry={nodes.Object_35.geometry} material={materials.material_0} />
          </group>
          <group position={[0.57, 1.58, -1.25]} scale={0.39}>
            <mesh geometry={nodes.Object_37.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_38.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_39.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_40.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_41.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_42.geometry} material={materials['Material.002']} />
          </group>
          <group position={[1.23, 1.25, -0.92]} scale={0.39}>
            <mesh geometry={nodes.Object_44.geometry} material={materials.Material} />
          </group>
          <group position={[0, -1.98, 0.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh geometry={nodes.Object_46.geometry} material={materials.material_0} />
          </group>
          <group position={[1.32, -1.67, -0.91]} scale={1.16}>
            <mesh geometry={nodes.Object_48.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_49.geometry} material={materials.Material} />
          </group>
        </group>
      </group>
    </e.group>
  )
}

useGLTF.preload('./models/gargoyle/scene.gltf')

export default Gargoyle
