/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useFrame } from '@react-three/fiber'
import React, { useRef } from 'react'
import { useGLTF, PivotControls } from '@react-three/drei'

const Sticker = (props) => {
  const { nodes, materials } = useGLTF('./models/sticker/prueba-sticker.gltf')
  const ref = useRef()

  useFrame(()=> {
    console.log(ref.current.position.x+"x");
    console.log(ref.current.position.y+"y");
    console.log(ref.current.position.z+"z");

  })

  return (
    <PivotControls scale={0} axisColors={["red", "green", "blue"]}>
      <group {...props} dispose={null} ref={ref}>
        <mesh castShadow  geometry={nodes.Cube.geometry} material={materials.Material} />
        <mesh castShadow  geometry={nodes['giphy_1_(4)'].geometry} material={materials['giphy 1 (4)']} position={[1.5, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      </group>
    </PivotControls>
  )
}

useGLTF.preload('./models/sticker/prueba-sticker.gltf')

export default Sticker
