/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: artasadmemon (https://sketchfab.com/artasadmemon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/iphone-illustration-e44a498de9a74c09bcc5b3474e3561ef
title: IPhone Illustration
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { editable as e } from '@theatre/r3f'

const Iphone = (props) => {
  const { nodes, materials } = useGLTF('./models/iphone/scene.gltf')
  return (
    <e.group theatreKey='Iphone' {...props} dispose={null} rotation={[0, 0, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          
          <group position={[0.81, 1.59, -3.11]} rotation={[Math.PI / 2, 0, 0]} scale={0.37}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.019']} />
          </group>
          <group position={[0.81, 1.59, -3.11]} rotation={[Math.PI / 2, 0, 0]} scale={0.5}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['Material.018']} />
          </group>
          <group position={[0.81, 1.59, -3.11]} rotation={[Math.PI / 2, 0, 0]} scale={0.68}>
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.019']} />
          </group>
          <group position={[0.81, 1.59, -3.11]} rotation={[Math.PI / 2, 0, 0]} scale={0.86}>
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.017']} />
          </group>
          <group position={[1.85, -0.48, -2.15]} rotation={[0, 0, -Math.PI / 2]} scale={[0.21, 0.21, 0.06]}>
            <group position={[0.01, 0.03, 0.35]} rotation={[0, 0, -Math.PI / 4]} scale={[1.62, 1.62, 5.54]}>
              <mesh geometry={nodes.Object_15.geometry} material={materials['Material.017']} />
            </group>
            <group position={[0.01, 0.03, -0.36]} rotation={[0, 0, Math.PI / 4]} scale={[1.62, 1.62, 5.54]}>
              <mesh geometry={nodes.Object_17.geometry} material={materials['Material.017']} />
            </group>
          </group>
          <group position={[1.85, -1, -2.15]} rotation={[0, 0, -Math.PI / 2]} scale={[0.21, 0.21, 0.06]}>
            <group position={[0.01, 0.03, 0.35]} rotation={[0, 0, -Math.PI / 4]} scale={[1.62, 1.62, 5.54]}>
              <mesh geometry={nodes.Object_20.geometry} material={materials['Material.017']} />
            </group>
            <group position={[0.01, 0.03, -0.36]} rotation={[0, 0, Math.PI / 4]} scale={[1.62, 1.62, 5.54]}>
              <mesh geometry={nodes.Object_22.geometry} material={materials['Material.017']} />
            </group>
          </group>
          <group position={[1.85, 0.02, -2.15]} rotation={[0, 0, -Math.PI / 2]} scale={[0.21, 0.21, 0.06]}>
            <group position={[0.01, 0.03, 0.35]} rotation={[0, 0, -Math.PI / 4]} scale={[1.62, 1.62, 5.54]}>
              <mesh geometry={nodes.Object_25.geometry} material={materials['Material.017']} />
            </group>
            <group position={[0.01, 0.03, -0.36]} rotation={[0, 0, Math.PI / 4]} scale={[1.62, 1.62, 5.54]}>
              <mesh geometry={nodes.Object_27.geometry} material={materials['Material.017']} />
            </group>
          </group>
          <group position={[1.74, -1.84, 1.67]} rotation={[0.73, 0.23, 0.56]} scale={0.41}>
            <group scale={0.61}>
              <mesh geometry={nodes.Object_30.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, Math.PI / 2, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_32.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, Math.PI / 4, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_34.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_36.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, Math.PI / 8, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_38.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 1.18, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_40.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 1.18, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_42.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, Math.PI / 8, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_44.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 0.2, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_46.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 1.37, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_48.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 0.98, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_50.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 0.59, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_52.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 0.59, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_54.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 0.98, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_56.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 1.37, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_58.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 0.2, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_60.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 0.1, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_62.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 1.47, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_64.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 0.88, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_66.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 0.69, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_68.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 0.49, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_70.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 1.08, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_72.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 1.28, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_74.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 0.29, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_76.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 0.29, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_78.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 1.28, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_80.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 1.08, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_82.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 0.49, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_84.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 0.69, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_86.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 0.88, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_88.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[0, 1.47, 0]} scale={0.61}>
              <mesh geometry={nodes.Object_90.geometry} material={materials['Material.005']} />
            </group>
            <group rotation={[-Math.PI, 0.1, -Math.PI]} scale={0.61}>
              <mesh geometry={nodes.Object_92.geometry} material={materials['Material.005']} />
            </group>
          </group>
          <group position={[-2.02, -0.49, -2.95]} rotation={[0, 0, 0.58]} scale={0.55}>
            <group position={[0.48, -2.32, 0]} rotation={[-Math.PI, 0, -1.81]} scale={1.1}>
              <mesh geometry={nodes.Object_96.geometry} material={materials['Material.016']} />
            </group>
            <mesh geometry={nodes.Object_94.geometry} material={materials['Material.016']} />
          </group>
          <group position={[-1.16, -1.3, -3.93]} rotation={[Math.PI / 2, 0, 0]} scale={1.01}>
            <mesh geometry={nodes.Object_98.geometry} material={materials['Material.021']} />
          </group>
          <group position={[1.45, 0.61, -1.44]} rotation={[0, 0, -Math.PI / 2]} scale={0.62}>
            <mesh geometry={nodes.Object_100.geometry} material={materials['Material.016']} />
          </group>
          <group position={[1.45, 0.35, -1.44]} rotation={[0, 0, -Math.PI / 2]} scale={0.62}>
            <mesh geometry={nodes.Object_102.geometry} material={materials['Material.016']} />
          </group>
          <group position={[1.45, 0.09, -1.44]} rotation={[0, 0, -Math.PI / 2]} scale={0.62}>
            <mesh geometry={nodes.Object_104.geometry} material={materials['Material.016']} />
          </group>
          <group position={[1.45, -0.2, -1.44]} rotation={[0, 0, -Math.PI / 2]} scale={0.62}>
            <mesh geometry={nodes.Object_106.geometry} material={materials['Material.016']} />
          </group>
          <group position={[0.09, 0.07, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.83, 1.67, 0.18]}>
            <group scale={[1.17, 0.58, 5.44]}>
              <group position={[0.82, 0.48, 0]}>
                <mesh geometry={nodes.Object_118.geometry} material={materials['Material.006']} />
              </group>
              <group position={[-0.82, 0.31, 0]} scale={[-1, 0.59, 1]}>
                <mesh geometry={nodes.Object_120.geometry} material={materials['Material.006']} />
              </group>
              <group position={[-0.82, 0.64, 0]} scale={[-1, 0.59, 1]}>
                <mesh geometry={nodes.Object_122.geometry} material={materials['Material.006']} />
              </group>
              <group position={[-0.82, 0.94, 0]} scale={[-1, 0.34, 1]}>
                <mesh geometry={nodes.Object_124.geometry} material={materials['Material.006']} />
              </group>
              <group position={[-0.03, 0.06, -0.81]} rotation={[Math.PI / 2, 0, 0]} scale={[-8.84, 8.84, 8.84]}>
                <mesh geometry={nodes.Object_126.geometry} material={materials['Material.014']} />
              </group>
              <mesh geometry={nodes.Object_128.geometry} material={materials['Material.009']} />
              <group position={[-0.14, -0.01, 0]}>
                <mesh geometry={nodes.Object_130.geometry} material={materials['Material.009']} />
              </group>
              <group position={[-0.26, -0.01, 0]}>
                <mesh geometry={nodes.Object_132.geometry} material={materials['Material.009']} />
              </group>
              <group position={[-0.44, 0, 0]}>
                <mesh geometry={nodes.Object_134.geometry} material={materials['Material.009']} />
              </group>
              <mesh geometry={nodes.Object_136.geometry} material={materials['Material.012']} />
              <group position={[-0.38, -0.2, 0]}>
                <mesh geometry={nodes.Object_138.geometry} material={materials['Material.012']} />
              </group>
              <group position={[0, -0.41, 0]}>
                <mesh geometry={nodes.Object_140.geometry} material={materials['Material.012']} />
              </group>
              <group position={[0.52, 1.37, -0.13]} scale={[0.04, 0.04, 0]}>
                <mesh geometry={nodes.Object_142.geometry} material={materials['Material.007']} />
              </group>
              <group position={[0.14, 1.17, -0.13]} scale={[0.04, 0.04, 0]}>
                <mesh geometry={nodes.Object_144.geometry} material={materials['Material.007']} />
              </group>
              <group position={[0.52, 0.97, -0.13]} scale={[0.04, 0.04, 0]}>
                <mesh geometry={nodes.Object_146.geometry} material={materials['Material.007']} />
              </group>
              <group position={[0.22, 1.55, 0.1]} scale={[0.02, 0.02, 0]}>
                <mesh geometry={nodes.Object_148.geometry} material={materials['Material.007']} />
              </group>
              <group position={[0.09, 1.55, 0.1]} scale={[0.02, 0.02, 0]}>
                <mesh geometry={nodes.Object_150.geometry} material={materials['Material.007']} />
              </group>
              <group position={[-0.04, 1.55, 0.1]} scale={[0.02, 0.02, 0]}>
                <mesh geometry={nodes.Object_152.geometry} material={materials['Material.007']} />
              </group>
              <group position={[-0.22, 1.56, 0.1]} scale={[0.02, 0.02, 0]}>
                <mesh geometry={nodes.Object_154.geometry} material={materials['Material.007']} />
              </group>
              <mesh geometry={nodes.Object_109.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_110.geometry} material={materials['Material.002']} />
              <mesh geometry={nodes.Object_111.geometry} material={materials['Material.003']} />
              <mesh geometry={nodes.Object_112.geometry} material={materials['Material.004']} />
              <mesh geometry={nodes.Object_113.geometry} material={materials['Material.006']} />
              <mesh geometry={nodes.Object_114.geometry} material={materials['Material.008']} />
              <mesh geometry={nodes.Object_115.geometry} material={materials['Material.010']} />
              <mesh geometry={nodes.Object_116.geometry} material={materials['Material.011']} />
            </group>
          </group>
          <group position={[2, 0.77, -1.1]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.36, 0.09, 0.36]}>
            <mesh geometry={nodes.Object_156.geometry} material={materials['Material.023']} />
          </group>
          <group position={[2.32, 0.77, -1.1]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.36, 0.09, 0.36]}>
            <mesh geometry={nodes.Object_158.geometry} material={materials['Material.018']} />
          </group>
          <group position={[1.29, 2.57, 0]} scale={0.06}>
            <mesh geometry={nodes.Object_160.geometry} material={materials['Material.005']} />
          </group>
          <group position={[-1.39, 1.77, 0.68]} scale={0.81}>
            <group scale={0.29}>
              <group scale={1.54}>
                <mesh geometry={nodes.Object_165.geometry} material={materials.material_0} />
              </group>
              <group rotation={[0, 0, -Math.PI / 2]} scale={1.54}>
                <mesh geometry={nodes.Object_167.geometry} material={materials.material_0} />
              </group>
              <group rotation={[0, 0, -Math.PI / 4]} scale={1.54}>
                <mesh geometry={nodes.Object_169.geometry} material={materials.material_0} />
              </group>
              <group rotation={[0, 0, -2.36]} scale={1.54}>
                <mesh geometry={nodes.Object_171.geometry} material={materials.material_0} />
              </group>
              <mesh geometry={nodes.Object_163.geometry} material={materials['Material.013']} />
            </group>
          </group>
          <group position={[-1.73, 0.54, -1.44]} rotation={[0, 0, -Math.PI / 2]} scale={0.62}>
            <mesh geometry={nodes.Object_173.geometry} material={materials['Material.016']} />
          </group>
          <group position={[-1.73, 0.34, -1.44]} rotation={[0, 0, -Math.PI / 2]} scale={0.62}>
            <mesh geometry={nodes.Object_175.geometry} material={materials['Material.016']} />
          </group>
          <group position={[-1.73, 0.14, -1.44]} rotation={[0, 0, -Math.PI / 2]} scale={0.62}>
            <mesh geometry={nodes.Object_177.geometry} material={materials['Material.016']} />
          </group>
          <group position={[0.56, -1.98, 0.48]}>
            <mesh geometry={nodes.Object_179.geometry} material={materials['Material.023']} />
          </group>
        </group>
      </group>
    </e.group>
  )
}

useGLTF.preload('./models/iphone/scene.gltf')

export default Iphone
