/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Cube2 = (props) => {
  const { nodes, materials } = useGLTF('./models/cube/cube2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Vidrio} scale={2.33} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} scale={1.18} />
    </group>
  )
}

useGLTF.preload('./models/cube/cube2.gltf')

export default Cube2