/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { editable as e } from '@theatre/r3f'

const Totem1 = (props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/totem1/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <e.group theatreKey='Totem1' ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[-0.68, -1.41, 0.94]} rotation={[-1.6, -0.2, 0.29]} scale={1}>
          <group name="part1objcleanermaterialmergergles">
            <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.body} />
            <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.tail} />
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.tail} />
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.engine} />
            <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.engine} />
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.tail} />
            <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.wings} />
          </group>
        </group>
        <group name="Sketchfab_model001" position={[-1.83, -2.22, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.26}>
          <group name="cloud_testFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="Plane001_1" position={[-0.79, 0, -5.26]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model002" position={[1.61, -2.22, -1.74]} rotation={[-Math.PI / 2, 0, 0]} scale={0.47}>
          <group name="cloud_testFBX001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode001">
              <group name="Plane001001" position={[-0.79, 0, -5.26]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Plane001_08_-_Default_0001" geometry={nodes['Plane001_08_-_Default_0001'].geometry} material={materials['08_-_Default.001']} position={[0, 0, 0.95]} scale={0.64} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model003" position={[-1.83, -2.22, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.26}>
          <group name="cloud_testFBX002" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode002">
              <group name="Plane001002" position={[-0.79, 0, -5.26]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Plane001_08_-_Default_0002" geometry={nodes['Plane001_08_-_Default_0002'].geometry} material={materials['08_-_Default.002']} position={[2.31, 0, 3.52]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model004" position={[-0.65, -1.1, 0.35]} rotation={[-Math.PI / 2, 0, 0]} scale={0.26}>
          <group name="cloud_testFBX003" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode003">
              <group name="Plane001003" position={[-0.79, 0, -5.26]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Plane001_08_-_Default_0003" geometry={nodes['Plane001_08_-_Default_0003'].geometry} material={materials['08_-_Default.003']} position={[0, 0, -1.01]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model005" position={[-0.31, -1.47, -0.85]} rotation={[-1.67, 0.02, 0.76]} scale={0.33}>
          <group name="cloud_testFBX004" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode004">
              <group name="Plane001004" position={[-0.79, 0, -5.26]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh name="Plane001_08_-_Default_0004" geometry={nodes['Plane001_08_-_Default_0004'].geometry} material={materials['08_-_Default.004']} position={[0, 0, -1.01]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model006" position={[0.82, -1.14, -1.28]} rotation={[Math.PI / 2, 0.04, 0]} scale={1.02}>
          <group name="2f669b7c569f4be89c93cd5b178d4b94fbx" rotation={[-Math.PI, 0, 0]}>
            <group name="RootNode005">
              <group name="Layer_2base">
                <mesh name="Layer_2base__0" geometry={nodes.Layer_2base__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Layer_4mic_head">
                <mesh name="Layer_4mic_head__0" geometry={nodes.Layer_4mic_head__0.geometry} material={materials['Scene_-_Root']} />
                <mesh name="Layer_4mic_head__0001" geometry={nodes.Layer_4mic_head__0001.geometry} material={materials['Scene_-_Root']} />
              </group>
            </group>
          </group>
        </group>
        <mesh name="tango_d1os_v3@4x" geometry={nodes['tango_d1os_v3@4x'].geometry} material={materials['tango d1os v3@4x']} position={[-0.88, 1.04, -0.72]} rotation={[Math.PI / 2, 0, 0]} scale={0.41} />
        <mesh name="diego" geometry={nodes.diego.geometry} material={materials.diego} position={[0, 0, -4.41]} rotation={[Math.PI / 2, 0, 0]} scale={3.67} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.017']} position={[0.73, 0.08, 0]} rotation={[0, 0, -2.36]} scale={0.25} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[1.07, 0.88, -3.2]} scale={0.68} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={nodes.Plane002.material} position={[-0.43, -1.13, -3.85]} scale={0.48} />
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[0.29, -0.16, -0.77]} scale={0.03} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.016']} position={[-1.77, -1.01, -4.71]} scale={[0.94, 0.94, 1.07]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.018']} position={[0.98, 1.03, -0.36]} rotation={[0, 0.07, 0]} scale={0.57} />
        <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={nodes.Plane004.material} position={[0.75, -1.06, -3.69]} scale={1.27} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.017']} position={[-1.58, -0.09, -1.41]} scale={0.42} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.016']} position={[1.58, -0.38, -3.38]} />
      </group>
    </e.group>
  )
}

useGLTF.preload('./models/totem1/scene.gltf')

export default Totem1
