/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { editable as e } from '@theatre/r3f'

const Totem1 = (props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/totem1/totem_1_NUEVAS_NUBES.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <e.group theatreKey='Totem1' ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[-0.68, -0.66, -0.95]} rotation={[-1.78, -0.36, 0.29]} scale={1.35}>
          <group name="part1objcleanermaterialmergergles">
            <mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.body} />
            <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.tail} />
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.tail} />
            <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.engine} />
            <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.engine} />
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.tail} />
            <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.wings} />
          </group>
        </group>
        <group name="Sketchfab_model001" position={[-1.83, -2.22, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.26}>
          <group name="cloud_testFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="Plane001_1" position={[-0.79, 0, -5.26]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model002" position={[1.61, -2.22, -1.74]} rotation={[-Math.PI / 2, 0, 0]} scale={0.47}>
          <group name="cloud_testFBX001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode001">
              <group name="Plane001001" position={[-0.79, 0, -5.26]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model003" position={[-1.83, -2.22, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.26}>
          <group name="cloud_testFBX002" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode002">
              <group name="Plane001002" position={[-0.79, 0, -5.26]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model004" position={[-0.65, -1.1, -0.31]} rotation={[-Math.PI / 2, 0, 0]} scale={0.26}>
          <group name="cloud_testFBX003" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode003">
              <group name="Plane001003" position={[-0.79, 0, -5.26]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Sketchfab_model005" position={[-0.31, -1.47, -0.85]} rotation={[-1.67, 0.02, 0.76]} scale={0.33}>
          <group name="cloud_testFBX004" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode004">
              <group name="Plane001004" position={[-0.79, 0, -5.26]} rotation={[-Math.PI / 2, 0, 0]} />
            </group>
          </group>
        </group>
        <group name="Plane001" position={[1.07, 0.88, -3.2]} scale={0.68} />
        <group name="Plane002" position={[-0.43, -1.13, -3.85]} scale={0.48} />
        <group name="Sketchfab_model006" position={[0.82, -1.14, -2.46]} rotation={[-Math.PI, 0, 0]} scale={1.38}>
          <group name="2f669b7c569f4be89c93cd5b178d4b94fbx" rotation={[1.56, -0.08, -1.01]}>
            <group name="RootNode005">
              <group name="Layer_2base">
                <mesh name="Layer_2base__0" geometry={nodes.Layer_2base__0.geometry} material={materials['Scene_-_Root']} />
              </group>
              <group name="Layer_4mic_head">
                <mesh name="Layer_4mic_head__0" geometry={nodes.Layer_4mic_head__0.geometry} material={materials['Scene_-_Root']} />
                <mesh name="Layer_4mic_head__0001" geometry={nodes.Layer_4mic_head__0001.geometry} material={materials['Scene_-_Root']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model007" position={[-1.96, -1.07, 0]} rotation={[-1.63, -0.05, -1.37]} scale={0.15}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube001_5" position={[1.68, 2.58, -11.41]}>
                <mesh name="Object_6001" geometry={nodes.Object_6001.geometry} material={materials.normal} position={[-7.03, -3.75, -2.26]} scale={[0.95, 0.95, 1.17]} />
              </group>
              <group name="Cube002_6" position={[-5.65, -1.87, -22.92]} scale={1.32}>
                <mesh name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials.normal} position={[-4.76, -0.67, 5.23]} scale={[0.68, 0.5, 0.68]} />
              </group>
              <group name="Cube_4" position={[0.34, 0.14, -3.53]}>
                <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials.normal} position={[-15.73, -3, -19.87]} rotation={[0.08, -0.29, 0.03]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Plane004" position={[0.75, -1.06, -3.69]} scale={1.27} />
        <group name="Sketchfab_model008" position={[-1.14, -1.07, 0]} rotation={[-1.63, -0.05, -1.37]} scale={0.05}>
          <group name="root001">
            <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube001_5001" position={[1.68, 2.58, -11.41]}>
                <mesh name="Object_6002" geometry={nodes.Object_6002.geometry} material={materials['normal.001']} position={[-22.44, -5.98, 15.9]} scale={[1.63, 1.63, 2.01]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model009" position={[-0.92, -1.11, -1.53]} rotation={[-1.5, 0.04, 1.52]} scale={0.07}>
          <group name="root002">
            <group name="GLTF_SceneRootNode002" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube001_5002" position={[1.68, 2.58, -11.41]}>
                <mesh name="Object_6003" geometry={nodes.Object_6003.geometry} material={materials['normal.002']} position={[-22.44, -5.98, 15.9]} scale={[1.63, 1.63, 2.01]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model010" position={[1.27, -1.15, -0.34]} rotation={[-1.63, -0.05, -1.37]} scale={0.06}>
          <group name="root003">
            <group name="GLTF_SceneRootNode003" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube001_5003" position={[1.68, 2.58, -11.41]}>
                <mesh name="Object_6004" geometry={nodes.Object_6004.geometry} material={materials['normal.003']} position={[-22.44, -5.98, 15.9]} scale={[1.63, 1.63, 2.01]} />
              </group>
            </group>
          </group>
        </group>
        <mesh name="tango_d1os_v3@4x" geometry={nodes['tango_d1os_v3@4x'].geometry} material={materials['tango d1os v3@4x']} position={[-0.88, 1.04, -0.72]} rotation={[Math.PI / 2, 0, 0]} scale={0.41} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.017']} position={[0.71, 0.55, 0]} rotation={[0, 0, -2.36]} scale={0.25} />
        <mesh name="totem_1_diego_(1)" geometry={nodes['totem_1_diego_(1)'].geometry} material={materials['totem_1_diego (1)']} position={[0.11, -0.13, -1.93]} rotation={[Math.PI / 2, 0, 0]} scale={2.48} />
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[0.29, -0.16, -0.77]} scale={0.03} />
        <mesh name="totem_1_fondo_-_copia2_00231" geometry={nodes['totem_1_fondo_-_copia2_00231'].geometry} material={materials['totem_1_fondo - copia2_00231']} position={[0, 0, -4.01]} rotation={[Math.PI / 2, 0, 3.13]} scale={3.92} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.016']} position={[-1.77, -1.01, -4.71]} scale={[0.94, 0.94, 1.07]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.018']} position={[0.98, 1.03, -0.36]} rotation={[0, 0.07, 0]} scale={0.57} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.017']} position={[-1.58, -0.09, -1.41]} scale={0.42} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.016']} position={[1.58, -0.38, -3.38]} />
      </group>
    </e.group>
  )
}
useGLTF.preload('./models/totem1/totem_1_NUEVAS_NUBES.gltf')

export default Totem1



