/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: artasadmemon (https://sketchfab.com/artasadmemon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/car-and-shapes-83262f3a91144443a809b1644a78f981
title: Car and Shapes
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { editable as e } from '@theatre/r3f'

const Car = (props) => {
  const { nodes, materials } = useGLTF('./models/car/scene.gltf')
  return (
    <e.group theatreKey='Car' {...props} dispose={null} rotation={[0, 0, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.63, 1.67, -0.77]} scale={0.05}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
          </group>
          <group position={[-0.86, 0.2, -1.41]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.017']} />
          </group>
          <group position={[0, 0.05, 0.15]} rotation={[0.37, -0.64, 0.23]} scale={[0.78, 0.58, 1.8]}>
            <group position={[0.79, -0.47, 0.52]} rotation={[0, 0, -Math.PI / 2]} scale={[0.45, 0.34, 0.15]}>
              <mesh geometry={nodes.Object_11.geometry} material={materials['Material.005']} />
              <mesh geometry={nodes.Object_12.geometry} material={materials['Material.008']} />
              <mesh geometry={nodes.Object_13.geometry} material={materials['Material.019']} />
            </group>
            <group position={[-0.78, -0.47, 0.52]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.45, 0.34, 0.15]}>
              <mesh geometry={nodes.Object_15.geometry} material={materials['Material.019']} />
              <mesh geometry={nodes.Object_16.geometry} material={materials['Material.005']} />
              <mesh geometry={nodes.Object_17.geometry} material={materials['Material.008']} />
            </group>
            <group position={[0.8, -0.47, -0.48]} rotation={[0, 0, -Math.PI / 2]} scale={[0.45, 0.34, 0.15]}>
              <mesh geometry={nodes.Object_19.geometry} material={materials['Material.019']} />
              <mesh geometry={nodes.Object_20.geometry} material={materials['Material.005']} />
              <mesh geometry={nodes.Object_21.geometry} material={materials['Material.008']} />
            </group>
            <group position={[-0.79, -0.47, -0.48]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.45, 0.34, 0.15]}>
              <mesh geometry={nodes.Object_23.geometry} material={materials['Material.019']} />
              <mesh geometry={nodes.Object_24.geometry} material={materials['Material.005']} />
              <mesh geometry={nodes.Object_25.geometry} material={materials['Material.008']} />
            </group>
            <group position={[0.01, -0.09, 0.93]} scale={[0.09, 0.06, 0.02]}>
              <mesh geometry={nodes.Object_27.geometry} material={materials['Material.002']} />
              <mesh geometry={nodes.Object_28.geometry} material={materials['Material.007']} />
              <mesh geometry={nodes.Object_29.geometry} material={materials['Material.013']} />
            </group>
            <group position={[0.01, -0.09, 0.95]} scale={[1.29, 1.73, 0.56]}>
              <mesh geometry={nodes.Object_31.geometry} material={materials['Material.001']} />
              <mesh geometry={nodes.Object_32.geometry} material={materials['Material.002']} />
              <mesh geometry={nodes.Object_33.geometry} material={materials['Material.003']} />
              <mesh geometry={nodes.Object_34.geometry} material={materials['Material.006']} />
              <mesh geometry={nodes.Object_35.geometry} material={materials['Material.011']} />
              <mesh geometry={nodes.Object_36.geometry} material={materials['Material.012']} />
              <mesh geometry={nodes.Object_37.geometry} material={materials['Material.007']} />
              <mesh geometry={nodes.Object_38.geometry} material={materials['Material.009']} />
              <mesh geometry={nodes.Object_39.geometry} material={materials['Material.010']} />
              <mesh geometry={nodes.Object_40.geometry} material={materials['Material.013']} />
              <mesh geometry={nodes.Object_41.geometry} material={materials['Material.014']} />
            </group>
            <group position={[0.01, -0.09, 0.95]} scale={[1.29, 1.73, 0.56]}>
              <mesh geometry={nodes.Object_43.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.01, -0.09, 0.95]} scale={[1.29, 1.73, 0.56]}>
              <mesh geometry={nodes.Object_45.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.01, -0.07, 0.95]} scale={[1.29, 1.73, 0.56]}>
              <mesh geometry={nodes.Object_47.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.01, -0.09, -0.2]} scale={[0.68, 0.87, 0.46]}>
              <mesh geometry={nodes.Object_49.geometry} material={materials['Material.009']} />
            </group>
            <group position={[0.42, 0.34, 0.26]} rotation={[0.63, -0.14, -0.19]} scale={[1.13, 1.26, 0.93]}>
              <mesh geometry={nodes.Object_51.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.66, 0.14, 0.38]} rotation={[0.06, -0.05, -0.61]} scale={[0.09, 0.1, 0.05]}>
              <mesh geometry={nodes.Object_53.geometry} material={materials['Material.009']} />
            </group>
          </group>
          <group position={[0, 0, -2.54]} scale={1.08}>
            <mesh geometry={nodes.Object_55.geometry} material={materials['Material.016']} />
          </group>
          <group position={[1.03, -0.5, -0.36]} rotation={[0, 0.07, 0]}>
            <mesh geometry={nodes.Object_57.geometry} material={materials['Material.018']} />
          </group>
          <group position={[1.58, -0.38, -3.38]}>
            <mesh geometry={nodes.Object_59.geometry} material={materials['Material.016']} />
          </group>
          <group position={[1.07, 0.88, -3.2]} scale={0.68}>
            <mesh geometry={nodes.Object_61.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_62.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_63.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_64.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_65.geometry} material={materials.material_0} />
          </group>
          <group position={[-0.43, -1.13, -3.85]} scale={0.48}>
            <mesh geometry={nodes.Object_67.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_68.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_69.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_70.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_71.geometry} material={materials.material_0} />
          </group>
          <group position={[0, 0, -5.86]} rotation={[0, 0, Math.PI / 3]}>
            <mesh geometry={nodes.Object_73.geometry} material={materials['Material.016']} />
          </group>
          <group position={[0, 0, -5.86]} rotation={[0, 0, 1.4]}>
            <mesh geometry={nodes.Object_75.geometry} material={materials['Material.016']} />
          </group>
          <group position={[0, 0, -5.86]} rotation={[0, 0, 1.75]}>
            <mesh geometry={nodes.Object_77.geometry} material={materials['Material.016']} />
          </group>
          <group position={[0, 0, -5.86]} rotation={[0, 0, 2.09]}>
            <mesh geometry={nodes.Object_79.geometry} material={materials['Material.017']} />
          </group>
          <group position={[0, 0, -5.86]} rotation={[0, 0, 2.44]}>
            <mesh geometry={nodes.Object_81.geometry} material={materials['Material.017']} />
          </group>
          <group rotation={[0, 0, -2.36]}>
            <mesh geometry={nodes.Object_83.geometry} material={materials['Material.017']} />
          </group>
          <group position={[0.75, -1.06, -3.69]} scale={1.27}>
            <mesh geometry={nodes.Object_85.geometry} material={materials.material_0} />
            <mesh geometry={nodes.Object_86.geometry} material={materials.material_0} />
          </group>
          <group position={[-0.55, 0.93, -3.73]} scale={0.55}>
            <mesh geometry={nodes.Object_88.geometry} material={materials['Material.018']} />
          </group>
          <group position={[1.69, 1.59, -1.66]} rotation={[Math.PI / 2, 0.07, 0]} scale={1.63}>
            <mesh geometry={nodes.Object_90.geometry} material={materials['Material.017']} />
          </group>
        </group>
      </group>
    </e.group>
  )
}

useGLTF.preload('./models/car/scene.gltf')

export default Car
